spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/h2/apigen;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: sa
      password:

snowflake:
  workerId: 1
  datacenterId: 1