spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/h2/apigen;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: sa
      password:
snowflake:
  workerId: 1
  datacenterId: 1
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hotstrip.runapi.domain.model